version: '3.8'

services:
  backend:
    build:
      context: ./web_ui/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./web_ui/uploads:/app/uploads
      - ./web_ui/results:/app/results
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./web_ui/frontend
    command: npm start
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  imputation:
    build: .
    volumes:
      - ./static_files:/imputation/static_files
      - ./web_ui/uploads:/imputation/uploads
      - ./web_ui/results:/imputation/results
    environment:
      - JAVA_OPTS=-Xmx8g
    # This service is started by the backend as needed, not on up
    entrypoint: ["sleep", "infinity"]