version: '3.8'

services:
  imputation:
    build: .
    volumes:
      - ./static_files:/imputation/static_files
      - ./web_ui/uploads:/imputation/uploads
      - ./web_ui/results:/imputation/results
    environment:
      - JAVA_OPTS=-Xmx8g
      - JOB_UUID=${JOB_UUID:-default}
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 8G
    # Remove hardcoded command - will be passed by FastAPI
    # command: ["target_genomes/genome_AB.txt"]
    # Uncomment the line below to run interactively
    # stdin_open: true
    # tty: true 